### ISSUE TITLE
Add alternative for mesa (hadrened/ colored clay) blocks.

### ISSUE THREAD

**Issue by sofar** [sofar/mcimport#4]

**Comment by RHRhino** [comment]
What do you think:
Would it make sense to create a "mc block mod" for minetest which contains all missing decorative blocks (so no redstone stuff).

**Comment by sofar** [comment]
I purposely chose not to go that route - there are already mods that do exactly that, but the problem is that they only create blocks, lack recipes, and lack minetest integration. I'd rather pick a well-maintained mod that actually cooperates and provides some playtime value.

**Comment by sofar** [comment]
d78ac5ad2be195d74279e89cb1d7654d9d0f03b8
