### ISSUE TITLE
xpanes:pane connection problems

### ISSUE THREAD

**Issue by RHRhino** [sofar/mcimport#6]
The connections of xpanes:pane don't work.
![screenshot_20160318_144611](https://cloud.githubusercontent.com/assets/6941454/13879585/7ff440ea-ed18-11e5-8abf-dfcf6c2ddbfe.png)

**Comment by sofar** [comment]
It's going to be really hard to fix this without this: https://www.youtube.com/watch?v=13M6Hz8oQ1I&index=2&list=PL0q7atYslWifTuX60rtCaocQiYUSdtZJP. And even then I don't think this will be easy.

**Comment by sofar** [comment]
Actually, once the new xpanes lands upstream, these panes will get auto-fixed and look great with no futher action needed in mcimport.
